spring:
  application:
    name: internet-banking-eureka-server
    
server:
  port: 8761
  
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    eureka-connection-idle-timeout-seconds: 35
    eureka-server-connect-timeout-seconds: 35