spring:
  application:
    name: internet-banking-payments-service
  datasource:
    url: jdbc:mysql://localhost:3306/internet_banking    
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update      
    properties:
     hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    
server:
  port: 8087
